# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                user_id = 'h0z968412-2451-4bbd-42h4-057l715d917m',
                email = 'john.doe@company.dev',
                full_name = 'John Doe',
                first_name = 'John',
                last_name = 'Doe',
                position = 'Senior Engineer',
                hr_idp_status = 'ACTIVE'
            )
        else:
            return User(
                user_id = 'h0z968412-2451-4bbd-42h4-057l715d917m',
                email = 'john.doe@company.dev',
                full_name = 'John Doe',
                first_name = 'John',
                last_name = 'Doe',
                position = 'Senior Engineer',
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
