# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_remote_info_github_enterprise_role import ResourceRemoteInfoGithubEnterpriseRole

class TestResourceRemoteInfoGithubEnterpriseRole(unittest.TestCase):
    """ResourceRemoteInfoGithubEnterpriseRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRemoteInfoGithubEnterpriseRole:
        """Test ResourceRemoteInfoGithubEnterpriseRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRemoteInfoGithubEnterpriseRole`
        """
        model = ResourceRemoteInfoGithubEnterpriseRole()
        if include_optional:
            return ResourceRemoteInfoGithubEnterpriseRole(
                role_id = '112233'
            )
        else:
            return ResourceRemoteInfoGithubEnterpriseRole(
                role_id = '112233',
        )
        """

    def testResourceRemoteInfoGithubEnterpriseRole(self):
        """Test ResourceRemoteInfoGithubEnterpriseRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
