"""
    Opal API

    Your Home For Developer Resources.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import opal
from opal.model.user import User
globals()['User'] = User
from opal.model.users_list import UsersList


class TestUsersList(unittest.TestCase):
    """UsersList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsersList(self):
        """Test UsersList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UsersList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
