# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_add_group_tag(self) -> None:
        """Test case for add_group_tag

        """
        pass

    def test_add_resource_tag(self) -> None:
        """Test case for add_resource_tag

        """
        pass

    def test_add_user_tag(self) -> None:
        """Test case for add_user_tag

        """
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        """
        pass

    def test_delete_tag_by_id(self) -> None:
        """Test case for delete_tag_by_id

        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        """
        pass

    def test_get_tag_by_id(self) -> None:
        """Test case for get_tag_by_id

        Get tag by ID
        """
        pass

    def test_get_tags(self) -> None:
        """Test case for get_tags

        Get tags
        """
        pass

    def test_remove_group_tag(self) -> None:
        """Test case for remove_group_tag

        """
        pass

    def test_remove_resource_tag(self) -> None:
        """Test case for remove_resource_tag

        """
        pass

    def test_remove_user_tag(self) -> None:
        """Test case for remove_user_tag

        """
        pass


if __name__ == '__main__':
    unittest.main()
