# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_paladin_info import UpdatePaladinInfo

class TestUpdatePaladinInfo(unittest.TestCase):
    """UpdatePaladinInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePaladinInfo:
        """Test UpdatePaladinInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePaladinInfo`
        """
        model = UpdatePaladinInfo()
        if include_optional:
            return UpdatePaladinInfo(
                name = 'paladin-agent-1',
                monitor_mode = True,
                admin_view_only = True,
                enabled_connectors = [
                    'NOTION'
                    ],
                instructions = ''
            )
        else:
            return UpdatePaladinInfo(
                name = 'paladin-agent-1',
        )
        """

    def testUpdatePaladinInfo(self):
        """Test UpdatePaladinInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
