"""
    Opal API

    Your Home For Developer Resources.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import opal
from opal.model.message_channel_provider_enum import MessageChannelProviderEnum
from opal.model.message_channel_type_enum import MessageChannelTypeEnum
globals()['MessageChannelProviderEnum'] = MessageChannelProviderEnum
globals()['MessageChannelTypeEnum'] = MessageChannelTypeEnum
from opal.model.message_channel import MessageChannel


class TestMessageChannel(unittest.TestCase):
    """MessageChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageChannel(self):
        """Test MessageChannel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MessageChannel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
