# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.create_request_comment_request import CreateRequestCommentRequest

class TestCreateRequestCommentRequest(unittest.TestCase):
    """CreateRequestCommentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRequestCommentRequest:
        """Test CreateRequestCommentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRequestCommentRequest`
        """
        model = CreateRequestCommentRequest()
        if include_optional:
            return CreateRequestCommentRequest(
                comment = ''
            )
        else:
            return CreateRequestCommentRequest(
                comment = '',
        )
        """

    def testCreateRequestCommentRequest(self):
        """Test CreateRequestCommentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
