# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.group_remote_info_ramp_location import GroupRemoteInfoRampLocation

class TestGroupRemoteInfoRampLocation(unittest.TestCase):
    """GroupRemoteInfoRampLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupRemoteInfoRampLocation:
        """Test GroupRemoteInfoRampLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupRemoteInfoRampLocation`
        """
        model = GroupRemoteInfoRampLocation()
        if include_optional:
            return GroupRemoteInfoRampLocation(
                location_id = 'f4efe11c-221f-4b49-a1e4-33eaf96a49ee'
            )
        else:
            return GroupRemoteInfoRampLocation(
                location_id = 'f4efe11c-221f-4b49-a1e4-33eaf96a49ee',
        )
        """

    def testGroupRemoteInfoRampLocation(self):
        """Test GroupRemoteInfoRampLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
