# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.tokens_api import TokensApi


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokensApi()

    def tearDown(self) -> None:
        pass

    def test_delete_token(self) -> None:
        """Test case for delete_token

        Delete token
        """
        pass

    def test_get_tokens(self) -> None:
        """Test case for get_tokens

        Get tokens
        """
        pass


if __name__ == '__main__':
    unittest.main()
