# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_resource_info_list import UpdateResourceInfoList

class TestUpdateResourceInfoList(unittest.TestCase):
    """UpdateResourceInfoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateResourceInfoList:
        """Test UpdateResourceInfoList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateResourceInfoList`
        """
        model = UpdateResourceInfoList()
        if include_optional:
            return UpdateResourceInfoList(
                resources = [
                    {"resource_id":"f454d283-ca87-4a8a-bdbb-df212eca5353","name":"my-mongo-db","description":"This resource represents AWS IAM role \"SupportUser\".","admin_owner_id":"7c86c85d-0651-43e2-a748-d69d658418e8","max_duration":120,"require_manager_approval":false,"require_support_ticket":false}
                    ]
            )
        else:
            return UpdateResourceInfoList(
                resources = [
                    {"resource_id":"f454d283-ca87-4a8a-bdbb-df212eca5353","name":"my-mongo-db","description":"This resource represents AWS IAM role \"SupportUser\".","admin_owner_id":"7c86c85d-0651-43e2-a748-d69d658418e8","max_duration":120,"require_manager_approval":false,"require_support_ticket":false}
                    ],
        )
        """

    def testUpdateResourceInfoList(self):
        """Test UpdateResourceInfoList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
