# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_group_info import UpdateGroupInfo

class TestUpdateGroupInfo(unittest.TestCase):
    """UpdateGroupInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGroupInfo:
        """Test UpdateGroupInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGroupInfo`
        """
        model = UpdateGroupInfo()
        if include_optional:
            return UpdateGroupInfo(
                group_id = 'f454d283-ca87-4a87-bdbb-df212eca5353',
                name = 'api-group',
                description = 'This group represents Active Directory group "Payments Production Admin". We use this AD group to facilitate staging deployments and qualifying new releases.',
                admin_owner_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                max_duration = 120,
                recommended_duration = 120,
                require_manager_approval = False,
                require_support_ticket = False,
                folder_id = 'e27cb7b0-98e2-4555-9916-9e6d8ca6b079',
                require_mfa_to_approve = False,
                require_mfa_to_request = False,
                auto_approval = False,
                configuration_template_id = '06851574-e50d-40ca-8c78-f72ae6ab4304',
                request_template_id = '06851574-e50d-40ca-8c78-f72ae6ab4304',
                is_requestable = False,
                group_leader_user_ids = [
                    ''
                    ],
                extensions_duration_in_minutes = 120,
                request_configurations = [
                    {request_configuration_id=7c86c85d-0651-43e2-a748-d69d658418e8, organization_id=w86c85d-0651-43e2-a748-d69d658418e8, created_at=2021-01-06T20:00:00Z, updated_at=2021-01-06T20:00:00Z, condition={group_id=1b978423-db0a-4037-a4cf-f79c60cb67b3}, allow_requests=true, auto_approval=false, require_mfa_to_request=false, max_duration_minutes=120, recommended_duration_minutes=120, require_support_ticket=false, reviewer_stages=[{reviewer_stage_id=7c86c85d-0651-43e2-a748-d69d658418e8, owner_ids=[37cb7e41-12ba-46da-92ff-030abe0450b1, 37cb7e41-12ba-46da-92ff-030abe0450b2], stage=1}], priority=1}
                    ],
                request_configuration_list = {request_configurations=[{request_configuration_id=7c86c85d-0651-43e2-a748-d69d658418e8, organization_id=w86c85d-0651-43e2-a748-d69d658418e8, condition=null, allow_requests=true, auto_approval=false, require_mfa_to_request=false, max_duration_minutes=120, recommended_duration_minutes=120, require_support_ticket=false, reviewer_stages=[{reviewer_stage_id=7c86c85d-0651-43e2-a748-d69d658418e8, owner_ids=[37cb7e41-12ba-46da-92ff-030abe0450b1, 37cb7e41-12ba-46da-92ff-030abe0450b2], stage=1}], priority=0}, {request_configuration_id=7c86c85d-0651-43e2-a748-d69d658418e9, organization_id=w86c85d-0651-43e2-a748-d69d658418e8, condition={group_id=1b978423-db0a-4037-a4cf-f79c60cb67b4}, allow_requests=true, auto_approval=false, require_mfa_to_request=false, max_duration_minutes=120, recommended_duration_minutes=120, require_support_ticket=false, reviewer_stages=[{reviewer_stage_id=7c86c85d-0651-43e2-a748-d69d658418e8, owner_ids=[37cb7e41-12ba-46da-92ff-030abe0450b1, 37cb7e41-12ba-46da-92ff-030abe0450b2], stage=1}], priority=1}]},
                custom_request_notification = 'Check your email to register your account.',
                risk_sensitivity_override = 'UNKNOWN'
            )
        else:
            return UpdateGroupInfo(
                group_id = 'f454d283-ca87-4a87-bdbb-df212eca5353',
        )
        """

    def testUpdateGroupInfo(self):
        """Test UpdateGroupInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
