# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.paginated_groups_list import PaginatedGroupsList

class TestPaginatedGroupsList(unittest.TestCase):
    """PaginatedGroupsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGroupsList:
        """Test PaginatedGroupsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGroupsList`
        """
        model = PaginatedGroupsList()
        if include_optional:
            return PaginatedGroupsList(
                next = 'cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw',
                previous = 'cj1sZXdwd2VycWVtY29zZnNkc2NzUWxNMEUxTXk0ME16UXpNallsTWtJ',
                results = [
                    {group_id=f454d283-ca87-4a8a-bdbb-df212eca5353, app_id=b5a5ca27-0ea3-4d86-9199-2126d57d1fbd, remote_id=037m2jsg218b2wb, remote_name=Finance Team, description=This group represents Active Directory group "Payments Production Admin". We use this AD group to facilitate staging deployments and qualifying new releases., admin_owner_id=7c86c85d-0651-43e2-a748-d69d658418e8, max_duration=120, require_manager_approval=false, require_support_ticket=false}
                    ]
            )
        else:
            return PaginatedGroupsList(
                results = [
                    {group_id=f454d283-ca87-4a8a-bdbb-df212eca5353, app_id=b5a5ca27-0ea3-4d86-9199-2126d57d1fbd, remote_id=037m2jsg218b2wb, remote_name=Finance Team, description=This group represents Active Directory group "Payments Production Admin". We use this AD group to facilitate staging deployments and qualifying new releases., admin_owner_id=7c86c85d-0651-43e2-a748-d69d658418e8, max_duration=120, require_manager_approval=false, require_support_ticket=false}
                    ],
        )
        """

    def testPaginatedGroupsList(self):
        """Test PaginatedGroupsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
