# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_remote_info_databricks_function import ResourceRemoteInfoDatabricksFunction

class TestResourceRemoteInfoDatabricksFunction(unittest.TestCase):
    """ResourceRemoteInfoDatabricksFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRemoteInfoDatabricksFunction:
        """Test ResourceRemoteInfoDatabricksFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRemoteInfoDatabricksFunction`
        """
        model = ResourceRemoteInfoDatabricksFunction()
        if include_optional:
            return ResourceRemoteInfoDatabricksFunction(
                metastore_id = '12345678-1234-1234-1234-123456789012',
                full_name = 'my_catalog.my_schema.my_function'
            )
        else:
            return ResourceRemoteInfoDatabricksFunction(
                metastore_id = '12345678-1234-1234-1234-123456789012',
                full_name = 'my_catalog.my_schema.my_function',
        )
        """

    def testResourceRemoteInfoDatabricksFunction(self):
        """Test ResourceRemoteInfoDatabricksFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
