# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.group_remote_info_zendesk_organization import GroupRemoteInfoZendeskOrganization

class TestGroupRemoteInfoZendeskOrganization(unittest.TestCase):
    """GroupRemoteInfoZendeskOrganization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupRemoteInfoZendeskOrganization:
        """Test GroupRemoteInfoZendeskOrganization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupRemoteInfoZendeskOrganization`
        """
        model = GroupRemoteInfoZendeskOrganization()
        if include_optional:
            return GroupRemoteInfoZendeskOrganization(
                organization_id = '67890'
            )
        else:
            return GroupRemoteInfoZendeskOrganization(
                organization_id = '67890',
        )
        """

    def testGroupRemoteInfoZendeskOrganization(self):
        """Test GroupRemoteInfoZendeskOrganization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
