# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_custom_access_level_list import ResourceCustomAccessLevelList

class TestResourceCustomAccessLevelList(unittest.TestCase):
    """ResourceCustomAccessLevelList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceCustomAccessLevelList:
        """Test ResourceCustomAccessLevelList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceCustomAccessLevelList`
        """
        model = ResourceCustomAccessLevelList()
        if include_optional:
            return ResourceCustomAccessLevelList(
                custom_access_levels = [
                    opal_security.models.resource_custom_access_level_response.ResourceCustomAccessLevelResponse(
                        resource_custom_access_level_id = '', 
                        resource_id = '', 
                        access_level = {access_level_name=AdminRole, access_level_remote_id=arn:aws:iam::590304332660:role/AdministratorAccess}, 
                        policy = '', 
                        requestable_by_default = True, 
                        stackable_sensitivity_index = 56, 
                        member_resource_ids = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ResourceCustomAccessLevelList(
                custom_access_levels = [
                    opal_security.models.resource_custom_access_level_response.ResourceCustomAccessLevelResponse(
                        resource_custom_access_level_id = '', 
                        resource_id = '', 
                        access_level = {access_level_name=AdminRole, access_level_remote_id=arn:aws:iam::590304332660:role/AdministratorAccess}, 
                        policy = '', 
                        requestable_by_default = True, 
                        stackable_sensitivity_index = 56, 
                        member_resource_ids = [
                            ''
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testResourceCustomAccessLevelList(self):
        """Test ResourceCustomAccessLevelList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
