# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_access_level_list import ResourceAccessLevelList

class TestResourceAccessLevelList(unittest.TestCase):
    """ResourceAccessLevelList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceAccessLevelList:
        """Test ResourceAccessLevelList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceAccessLevelList`
        """
        model = ResourceAccessLevelList()
        if include_optional:
            return ResourceAccessLevelList(
                results = [
                    {access_level_name=AdminRole, access_level_remote_id=arn:aws:iam::590304332660:role/AdministratorAccess}
                    ]
            )
        else:
            return ResourceAccessLevelList(
        )
        """

    def testResourceAccessLevelList(self):
        """Test ResourceAccessLevelList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
