# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.viewer_campaign_item import ViewerCampaignItem

class TestViewerCampaignItem(unittest.TestCase):
    """ViewerCampaignItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewerCampaignItem:
        """Test ViewerCampaignItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewerCampaignItem`
        """
        model = ViewerCampaignItem()
        if include_optional:
            return ViewerCampaignItem(
                campaign_item_review_id = '',
                decision = 'APPROVED',
                note = '',
                decided_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                pending_decision = 'APPROVED',
                pending_note = '',
                updated_access_level_remote_id = '',
                pending_updated_access_level_remote_id = '',
                reassigned_to_reviewer_ids = [
                    ''
                    ],
                principal_id = '',
                principal_type = 'GROUP',
                entity_id = '',
                entity_type = 'GROUP',
                access_level_name = '',
                access_level_remote_id = '',
                granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                role_assignment_id = ''
            )
        else:
            return ViewerCampaignItem(
                campaign_item_review_id = '',
                principal_id = '',
                principal_type = 'GROUP',
                entity_id = '',
                entity_type = 'GROUP',
                granted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                role_assignment_id = '',
        )
        """

    def testViewerCampaignItem(self):
        """Test ViewerCampaignItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
