# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.event_stream_connection_type_enum import EventStreamConnectionTypeEnum

class TestEventStreamConnectionTypeEnum(unittest.TestCase):
    """EventStreamConnectionTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventStreamConnectionTypeEnum(self):
        """Test EventStreamConnectionTypeEnum"""
        # inst = EventStreamConnectionTypeEnum()

if __name__ == '__main__':
    unittest.main()
