# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_remote_info_azure_subscription import ResourceRemoteInfoAzureSubscription

class TestResourceRemoteInfoAzureSubscription(unittest.TestCase):
    """ResourceRemoteInfoAzureSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRemoteInfoAzureSubscription:
        """Test ResourceRemoteInfoAzureSubscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRemoteInfoAzureSubscription`
        """
        model = ResourceRemoteInfoAzureSubscription()
        if include_optional:
            return ResourceRemoteInfoAzureSubscription(
                resource_id = '/subscriptions/00000000-0000-0000-0000-000000000000'
            )
        else:
            return ResourceRemoteInfoAzureSubscription(
                resource_id = '/subscriptions/00000000-0000-0000-0000-000000000000',
        )
        """

    def testResourceRemoteInfoAzureSubscription(self):
        """Test ResourceRemoteInfoAzureSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
