# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.paladin_context_source_kind import PaladinContextSourceKind

class TestPaladinContextSourceKind(unittest.TestCase):
    """PaladinContextSourceKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaladinContextSourceKind(self):
        """Test PaladinContextSourceKind"""
        # inst = PaladinContextSourceKind()

if __name__ == '__main__':
    unittest.main()
