# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_campaign_configuration_info import UpdateCampaignConfigurationInfo

class TestUpdateCampaignConfigurationInfo(unittest.TestCase):
    """UpdateCampaignConfigurationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCampaignConfigurationInfo:
        """Test UpdateCampaignConfigurationInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCampaignConfigurationInfo`
        """
        model = UpdateCampaignConfigurationInfo()
        if include_optional:
            return UpdateCampaignConfigurationInfo(
                allow_self_review = False,
                send_reviewer_assignment_notification = True,
                allow_reviewer_reassignment = False,
                start_date = '2026-07-02T00:00:00.000+00:00',
                end_date = '2026-09-30T00:00:00.000+00:00',
                timezone = 'America/Los_Angeles',
                revoke_on = 'END',
                reminder_schedule = [7, 3, 1],
                reminder_include_manager = True,
                require_reason_on_denial = False,
                hide_ai_suggestions = False,
                custom_start_message = 'Please complete your reviews by Friday.',
                group_asset_visibility_policy = 'STRICT',
                cron_expression = '0 9 1 * *',
                recurring_duration_days = 14
            )
        else:
            return UpdateCampaignConfigurationInfo(
        )
        """

    def testUpdateCampaignConfigurationInfo(self):
        """Test UpdateCampaignConfigurationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
