# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.group_remote_info_devin_group import GroupRemoteInfoDevinGroup

class TestGroupRemoteInfoDevinGroup(unittest.TestCase):
    """GroupRemoteInfoDevinGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupRemoteInfoDevinGroup:
        """Test GroupRemoteInfoDevinGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupRemoteInfoDevinGroup`
        """
        model = GroupRemoteInfoDevinGroup()
        if include_optional:
            return GroupRemoteInfoDevinGroup(
                group_name = 'devin-group-01'
            )
        else:
            return GroupRemoteInfoDevinGroup(
                group_name = 'devin-group-01',
        )
        """

    def testGroupRemoteInfoDevinGroup(self):
        """Test GroupRemoteInfoDevinGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
