# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_campaign_info import UpdateCampaignInfo

class TestUpdateCampaignInfo(unittest.TestCase):
    """UpdateCampaignInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCampaignInfo:
        """Test UpdateCampaignInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCampaignInfo`
        """
        model = UpdateCampaignInfo()
        if include_optional:
            return UpdateCampaignInfo(
                name = 'Q3 Access Review (Updated)',
                configuration = {end_date=2026-09-30T00:00:00.000+00:00, timezone=America/Los_Angeles, allow_self_review=false}
            )
        else:
            return UpdateCampaignInfo(
        )
        """

    def testUpdateCampaignInfo(self):
        """Test UpdateCampaignInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
