# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.tags_list import TagsList

class TestTagsList(unittest.TestCase):
    """TagsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagsList:
        """Test TagsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagsList`
        """
        model = TagsList()
        if include_optional:
            return TagsList(
                tags = [
                    {tag_id=f290a738-5f9f-43c2-ad67-fa31ff0eb946, created_at=2022-01-23T04:56:07Z, updated_at=2022-02-23T01:34:07Z, user_creator_id=d4a7d928-783e-4599-8ec6-088d635a5bcc, key=database-name, value=redis_db}
                    ]
            )
        else:
            return TagsList(
                tags = [
                    {tag_id=f290a738-5f9f-43c2-ad67-fa31ff0eb946, created_at=2022-01-23T04:56:07Z, updated_at=2022-02-23T01:34:07Z, user_creator_id=d4a7d928-783e-4599-8ec6-088d635a5bcc, key=database-name, value=redis_db}
                    ],
        )
        """

    def testTagsList(self):
        """Test TagsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
