"""
    Opal API

    Your Home For Developer Resources.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import opal
from opal.model.session import Session
globals()['Session'] = Session
from opal.model.sessions_list import SessionsList


class TestSessionsList(unittest.TestCase):
    """SessionsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionsList(self):
        """Test SessionsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
