# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.session import Session

class TestSession(unittest.TestCase):
    """Session unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Session:
        """Test Session
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Session`
        """
        model = Session()
        if include_optional:
            return Session(
                connection_id = 'h0z968412-2451-4bbd-42h4-057l715d917m',
                user_id = '29827fb8-f2dd-4e80-9576-28e31e9934ac',
                resource_id = '1b978423-db0a-4037-a4cf-f79c60cb67b3',
                access_level = {access_level_name=AdminRole, access_level_remote_id=arn:aws:iam::590304332660:role/AdministratorAccess},
                expiration_date = '2022-01-23T04:56:07Z'
            )
        else:
            return Session(
                connection_id = 'h0z968412-2451-4bbd-42h4-057l715d917m',
                user_id = '29827fb8-f2dd-4e80-9576-28e31e9934ac',
                resource_id = '1b978423-db0a-4037-a4cf-f79c60cb67b3',
                access_level = {access_level_name=AdminRole, access_level_remote_id=arn:aws:iam::590304332660:role/AdministratorAccess},
                expiration_date = '2022-01-23T04:56:07Z',
        )
        """

    def testSession(self):
        """Test Session"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
