# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.request_comment import RequestComment

class TestRequestComment(unittest.TestCase):
    """RequestComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestComment:
        """Test RequestComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestComment`
        """
        model = RequestComment()
        if include_optional:
            return RequestComment(
                created_at = '2021-01-06T20:00:00Z',
                request_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                user_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                user_full_name = 'Jake Barnes',
                user_email = 'jake.barnes@company.com',
                comment = 'This is a comment.'
            )
        else:
            return RequestComment(
                created_at = '2021-01-06T20:00:00Z',
                request_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                user_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                comment = 'This is a comment.',
        )
        """

    def testRequestComment(self):
        """Test RequestComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
