# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.request_reviewer_stages import RequestReviewerStages

class TestRequestReviewerStages(unittest.TestCase):
    """RequestReviewerStages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestReviewerStages:
        """Test RequestReviewerStages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestReviewerStages`
        """
        model = RequestReviewerStages()
        if include_optional:
            return RequestReviewerStages(
                access_level_name = 'admin',
                access_level_remote_id = 'arn:aws:iam::490306337630:role/SupportUser',
                item_name = '',
                item_id = 'f454d283-ca87-4a8a-bdbb-df212eca5353',
                stages = [
                    opal_security.models.request_stage.RequestStage(
                        stage = 56, 
                        operator = 'AND', 
                        reviewers = [
                            opal_security.models.request_reviewer.RequestReviewer(
                                id = '', 
                                full_name = 'Jake Barnes', 
                                status = 'PENDING', )
                            ], )
                    ]
            )
        else:
            return RequestReviewerStages(
                item_name = '',
                item_id = 'f454d283-ca87-4a8a-bdbb-df212eca5353',
                stages = [
                    opal_security.models.request_stage.RequestStage(
                        stage = 56, 
                        operator = 'AND', 
                        reviewers = [
                            opal_security.models.request_reviewer.RequestReviewer(
                                id = '', 
                                full_name = 'Jake Barnes', 
                                status = 'PENDING', )
                            ], )
                    ],
        )
        """

    def testRequestReviewerStages(self):
        """Test RequestReviewerStages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
