# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.request_status_enum import RequestStatusEnum

class TestRequestStatusEnum(unittest.TestCase):
    """RequestStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestStatusEnum(self):
        """Test RequestStatusEnum"""
        # inst = RequestStatusEnum()

if __name__ == '__main__':
    unittest.main()
