# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.user_product_role_enum import UserProductRoleEnum

class TestUserProductRoleEnum(unittest.TestCase):
    """UserProductRoleEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserProductRoleEnum(self):
        """Test UserProductRoleEnum"""
        # inst = UserProductRoleEnum()

if __name__ == '__main__':
    unittest.main()
