# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.paladin_api import PaladinApi


class TestPaladinApi(unittest.TestCase):
    """PaladinApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaladinApi()

    def tearDown(self) -> None:
        pass

    def test_create_paladin(self) -> None:
        """Test case for create_paladin

        Create Paladin
        """
        pass

    def test_create_paladin_context_source(self) -> None:
        """Test case for create_paladin_context_source

        Add a Paladin context source
        """
        pass

    def test_delete_paladin(self) -> None:
        """Test case for delete_paladin

        Delete Paladin
        """
        pass

    def test_delete_paladin_context_source(self) -> None:
        """Test case for delete_paladin_context_source

        Remove a Paladin context source
        """
        pass

    def test_get_paladin(self) -> None:
        """Test case for get_paladin

        Get Paladin by ID
        """
        pass

    def test_get_paladin_from_name(self) -> None:
        """Test case for get_paladin_from_name

        Get Paladins by name
        """
        pass

    def test_list_paladin_context_sources(self) -> None:
        """Test case for list_paladin_context_sources

        List Paladin context sources
        """
        pass

    def test_update_paladin(self) -> None:
        """Test case for update_paladin

        Update Paladin
        """
        pass


if __name__ == '__main__':
    unittest.main()
