# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.opal_queries_api import OpalQueriesApi


class TestOpalQueriesApi(unittest.TestCase):
    """OpalQueriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpalQueriesApi()

    def tearDown(self) -> None:
        pass

    def test_run_opal_query(self) -> None:
        """Test case for run_opal_query

        Run an ad-hoc OpalQuery
        """
        pass


if __name__ == '__main__':
    unittest.main()
