# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.campaign import Campaign

class TestCampaign(unittest.TestCase):
    """Campaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Campaign:
        """Test Campaign
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Campaign`
        """
        model = Campaign()
        if include_optional:
            return Campaign(
                campaign_id = 'f454d283-ca87-4a8a-bdbb-df212eca5353',
                name = 'Q3 Access Review',
                status = 'ONGOING',
                is_template = False,
                created_at = '2026-07-01T00:00:00.000+00:00',
                updated_at = '2026-07-01T00:00:00.000+00:00',
                created_by_user_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
                configuration = {configuration_id=39a4d283-ca87-4a8a-bdbb-df212eca5fdb, created_at=2026-07-01T00:00:00.000+00:00, updated_at=2026-07-01T00:00:00.000+00:00, reviewer_assignment_policy=MANUALLY, allow_self_review=false, send_reviewer_assignment_notification=true, allow_reviewer_reassignment=false, end_date=2026-09-30T00:00:00.000+00:00, timezone=America/Los_Angeles, revoke_on=END, reminder_schedule=[7, 3, 1], reminder_include_manager=true, require_reason_on_denial=false, hide_ai_suggestions=false, group_asset_visibility_policy=STRICT, is_template=false},
                started_at = '2026-07-02T00:00:00.000+00:00',
                started_by_user_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
                stopped_at = '2026-07-10T00:00:00.000+00:00',
                stopped_by_user_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
                ended_at = '2026-07-14T00:00:00.000+00:00',
                ended_by_user_id = '32acc112-21ff-4669-91c2-21e27683eaa1'
            )
        else:
            return Campaign(
                campaign_id = 'f454d283-ca87-4a8a-bdbb-df212eca5353',
                name = 'Q3 Access Review',
                status = 'ONGOING',
                is_template = False,
                created_at = '2026-07-01T00:00:00.000+00:00',
                updated_at = '2026-07-01T00:00:00.000+00:00',
                created_by_user_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
        )
        """

    def testCampaign(self):
        """Test Campaign"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
