# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.non_human_identities_api import NonHumanIdentitiesApi


class TestNonHumanIdentitiesApi(unittest.TestCase):
    """NonHumanIdentitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NonHumanIdentitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_nhis(self) -> None:
        """Test case for get_nhis

        """
        pass


if __name__ == '__main__':
    unittest.main()
