# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.request_stage import RequestStage

class TestRequestStage(unittest.TestCase):
    """RequestStage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestStage:
        """Test RequestStage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestStage`
        """
        model = RequestStage()
        if include_optional:
            return RequestStage(
                stage = 56,
                operator = 'AND',
                reviewers = [
                    opal_security.models.request_reviewer.RequestReviewer(
                        id = '', 
                        full_name = 'Jake Barnes', 
                        status = 'PENDING', )
                    ]
            )
        else:
            return RequestStage(
                stage = 56,
                operator = 'AND',
                reviewers = [
                    opal_security.models.request_reviewer.RequestReviewer(
                        id = '', 
                        full_name = 'Jake Barnes', 
                        status = 'PENDING', )
                    ],
        )
        """

    def testRequestStage(self):
        """Test RequestStage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
