# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_remote_info_oracle_fusion_role import ResourceRemoteInfoOracleFusionRole

class TestResourceRemoteInfoOracleFusionRole(unittest.TestCase):
    """ResourceRemoteInfoOracleFusionRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRemoteInfoOracleFusionRole:
        """Test ResourceRemoteInfoOracleFusionRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRemoteInfoOracleFusionRole`
        """
        model = ResourceRemoteInfoOracleFusionRole()
        if include_optional:
            return ResourceRemoteInfoOracleFusionRole(
                role_id = '123e4567-e89b-12d3-a456-426614174000'
            )
        else:
            return ResourceRemoteInfoOracleFusionRole(
                role_id = '123e4567-e89b-12d3-a456-426614174000',
        )
        """

    def testResourceRemoteInfoOracleFusionRole(self):
        """Test ResourceRemoteInfoOracleFusionRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
