# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.requests_api import RequestsApi


class TestRequestsApi(unittest.TestCase):
    """RequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestsApi()

    def tearDown(self) -> None:
        pass

    def test_approve_request(self) -> None:
        """Test case for approve_request

        """
        pass

    def test_create_request(self) -> None:
        """Test case for create_request

        """
        pass

    def test_create_request_comment(self) -> None:
        """Test case for create_request_comment

        """
        pass

    def test_deny_request(self) -> None:
        """Test case for deny_request

        """
        pass

    def test_get_request(self) -> None:
        """Test case for get_request

        Get request by ID
        """
        pass

    def test_get_request_comments(self) -> None:
        """Test case for get_request_comments

        """
        pass

    def test_get_requests(self) -> None:
        """Test case for get_requests

        Get requests
        """
        pass

    def test_get_requests_relay(self) -> None:
        """Test case for get_requests_relay

        Get requests via Relay
        """
        pass


if __name__ == '__main__':
    unittest.main()
