"""
    Opal API

    Your Home For Developer Resources.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import opal
from opal.model.visibility_enum import VisibilityEnum
globals()['VisibilityEnum'] = VisibilityEnum
from opal.model.update_resource_info import UpdateResourceInfo


class TestUpdateResourceInfo(unittest.TestCase):
    """UpdateResourceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateResourceInfo(self):
        """Test UpdateResourceInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateResourceInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
