# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.create_idp_group_mapping_request import CreateIdpGroupMappingRequest

class TestCreateIdpGroupMappingRequest(unittest.TestCase):
    """CreateIdpGroupMappingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIdpGroupMappingRequest:
        """Test CreateIdpGroupMappingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIdpGroupMappingRequest`
        """
        model = CreateIdpGroupMappingRequest()
        if include_optional:
            return CreateIdpGroupMappingRequest(
                alias = '',
                hidden_from_end_user = True
            )
        else:
            return CreateIdpGroupMappingRequest(
        )
        """

    def testCreateIdpGroupMappingRequest(self):
        """Test CreateIdpGroupMappingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
