# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.api.scoped_role_permissions_api import ScopedRolePermissionsApi


class TestScopedRolePermissionsApi(unittest.TestCase):
    """ScopedRolePermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScopedRolePermissionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_resource_scoped_role_permissions(self) -> None:
        """Test case for get_resource_scoped_role_permissions

        """
        pass

    def test_set_resource_scoped_role_permissions(self) -> None:
        """Test case for set_resource_scoped_role_permissions

        """
        pass


if __name__ == '__main__':
    unittest.main()
