# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_group_info_list import UpdateGroupInfoList

class TestUpdateGroupInfoList(unittest.TestCase):
    """UpdateGroupInfoList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGroupInfoList:
        """Test UpdateGroupInfoList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGroupInfoList`
        """
        model = UpdateGroupInfoList()
        if include_optional:
            return UpdateGroupInfoList(
                groups = [
                    {group_id=f454d283-ca87-4a87-bdbb-df212eca5353, description=This group represents Active Directory group "Payments Production Admin". We use this AD group to facilitate staging deployments and qualifying new releases., name=api-group, admin_owner_id=7c86c85d-0651-43e2-a748-d69d658418e8, max_duration=120, require_manager_approval=false, require_support_ticket=false}
                    ]
            )
        else:
            return UpdateGroupInfoList(
                groups = [
                    {group_id=f454d283-ca87-4a87-bdbb-df212eca5353, description=This group represents Active Directory group "Payments Production Admin". We use this AD group to facilitate staging deployments and qualifying new releases., name=api-group, admin_owner_id=7c86c85d-0651-43e2-a748-d69d658418e8, max_duration=120, require_manager_approval=false, require_support_ticket=false}
                    ],
        )
        """

    def testUpdateGroupInfoList(self):
        """Test UpdateGroupInfoList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
