# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.sync_task import SyncTask

class TestSyncTask(unittest.TestCase):
    """SyncTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncTask:
        """Test SyncTask
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncTask`
        """
        model = SyncTask()
        if include_optional:
            return SyncTask(
                id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                completed_at = '2023-10-01T12:00:00Z'
            )
        else:
            return SyncTask(
                id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                completed_at = '2023-10-01T12:00:00Z',
        )
        """

    def testSyncTask(self):
        """Test SyncTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
