# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_type_enum import ResourceTypeEnum

class TestResourceTypeEnum(unittest.TestCase):
    """ResourceTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceTypeEnum(self):
        """Test ResourceTypeEnum"""
        # inst = ResourceTypeEnum()

if __name__ == '__main__':
    unittest.main()
