# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.event_stream_connection import EventStreamConnection

class TestEventStreamConnection(unittest.TestCase):
    """EventStreamConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventStreamConnection:
        """Test EventStreamConnection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventStreamConnection`
        """
        model = EventStreamConnection()
        if include_optional:
            return EventStreamConnection(
                name = '',
                connection_type = 'WEBHOOK',
                enabled = True,
                webhook_url = '',
                credentials = opal_security.models.webhook_credentials.WebhookCredentials(
                    auth_type = 'NONE', 
                    api_key_credentials = [
                        opal_security.models.webhook_api_key_credential.WebhookApiKeyCredential(
                            id = '', 
                            name = '', 
                            value = '', 
                            location = 'HEADER', )
                        ], 
                    hmac_credential_1 = null, 
                    hmac_credential_2 = null, )
            )
        else:
            return EventStreamConnection(
                name = '',
                connection_type = 'WEBHOOK',
                enabled = True,
        )
        """

    def testEventStreamConnection(self):
        """Test EventStreamConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
