# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.update_resource_custom_access_level_info import UpdateResourceCustomAccessLevelInfo

class TestUpdateResourceCustomAccessLevelInfo(unittest.TestCase):
    """UpdateResourceCustomAccessLevelInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateResourceCustomAccessLevelInfo:
        """Test UpdateResourceCustomAccessLevelInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateResourceCustomAccessLevelInfo`
        """
        model = UpdateResourceCustomAccessLevelInfo()
        if include_optional:
            return UpdateResourceCustomAccessLevelInfo(
                access_level_name = '',
                policy = '',
                requestable_by_default = True,
                stackable_sensitivity_index = 56,
                clear_stackable_sensitivity_index = True
            )
        else:
            return UpdateResourceCustomAccessLevelInfo(
        )
        """

    def testUpdateResourceCustomAccessLevelInfo(self):
        """Test UpdateResourceCustomAccessLevelInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
