# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.user_attribute_selector import UserAttributeSelector

class TestUserAttributeSelector(unittest.TestCase):
    """UserAttributeSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAttributeSelector:
        """Test UserAttributeSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAttributeSelector`
        """
        model = UserAttributeSelector()
        if include_optional:
            return UserAttributeSelector(
                attribute = 'HR_IDP_STATUS',
                values = [
                    ''
                    ]
            )
        else:
            return UserAttributeSelector(
                attribute = 'HR_IDP_STATUS',
                values = [
                    ''
                    ],
        )
        """

    def testUserAttributeSelector(self):
        """Test UserAttributeSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
