# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.paladin import Paladin

class TestPaladin(unittest.TestCase):
    """Paladin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Paladin:
        """Test Paladin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Paladin`
        """
        model = Paladin()
        if include_optional:
            return Paladin(
                paladin_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
                name = 'paladin-agent-1',
                owner_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                monitor_mode = True,
                admin_view_only = True,
                enabled_connectors = [
                    'NOTION'
                    ],
                instructions = 'Approve read-only access; escalate anything that grants write access.'
            )
        else:
            return Paladin(
                paladin_id = '32acc112-21ff-4669-91c2-21e27683eaa1',
                name = 'paladin-agent-1',
                owner_id = '7c86c85d-0651-43e2-a748-d69d658418e8',
                monitor_mode = True,
                admin_view_only = True,
                enabled_connectors = [
                    'NOTION'
                    ],
                instructions = 'Approve read-only access; escalate anything that grants write access.',
        )
        """

    def testPaladin(self):
        """Test Paladin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
