# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.resource_remote_info_alicloud_ram_role import ResourceRemoteInfoAlicloudRamRole

class TestResourceRemoteInfoAlicloudRamRole(unittest.TestCase):
    """ResourceRemoteInfoAlicloudRamRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceRemoteInfoAlicloudRamRole:
        """Test ResourceRemoteInfoAlicloudRamRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceRemoteInfoAlicloudRamRole`
        """
        model = ResourceRemoteInfoAlicloudRamRole()
        if include_optional:
            return ResourceRemoteInfoAlicloudRamRole(
                role_arn = 'acs:ram::1234567890:role/MyRole'
            )
        else:
            return ResourceRemoteInfoAlicloudRamRole(
                role_arn = 'acs:ram::1234567890:role/MyRole',
        )
        """

    def testResourceRemoteInfoAlicloudRamRole(self):
        """Test ResourceRemoteInfoAlicloudRamRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
