# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opal_security.models.remote_user import RemoteUser

class TestRemoteUser(unittest.TestCase):
    """RemoteUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoteUser:
        """Test RemoteUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoteUser`
        """
        model = RemoteUser()
        if include_optional:
            return RemoteUser(
                user_id = '29827fb8-f2dd-4e80-9576-28e31e9934ac',
                remote_id = '1234567890',
                third_party_provider = GIT_HUB
            )
        else:
            return RemoteUser(
                user_id = '29827fb8-f2dd-4e80-9576-28e31e9934ac',
                remote_id = '1234567890',
                third_party_provider = GIT_HUB,
        )
        """

    def testRemoteUser(self):
        """Test RemoteUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
