# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CampaignItemStatusEnum(str, Enum):
    """
    Derived aggregate status for a campaign item. Matches the admin Reviews tab Status column labels (undecided items on a stopped campaign are PENDING, not a separate stopped status). 
    """

    """
    allowed enum values
    """
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    APPROVED = 'APPROVED'
    REVOKED = 'REVOKED'
    NO_ACTION = 'NO_ACTION'
    CHANGED_ROLE = 'CHANGED_ROLE'
    ADMIN_REVOKED = 'ADMIN_REVOKED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CampaignItemStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


