# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from opal_security.models.campaign_item_admin_override import CampaignItemAdminOverride
from opal_security.models.campaign_item_review import CampaignItemReview
from opal_security.models.campaign_item_status_enum import CampaignItemStatusEnum
from opal_security.models.campaign_item_target_type_enum import CampaignItemTargetTypeEnum
from opal_security.models.entity_type_enum import EntityTypeEnum
from opal_security.models.resource_access_level import ResourceAccessLevel
from typing import Optional, Set
from typing_extensions import Self

class CampaignItem(BaseModel):
    """
    A campaign review item — one direct access edge under review, matching a row on the admin Reviews tab. 
    """ # noqa: E501
    campaign_item_id: UUID = Field(description="The ID of the campaign item.")
    campaign_id: UUID = Field(description="The ID of the parent campaign.")
    target_type: CampaignItemTargetTypeEnum
    role_assignment_id: UUID = Field(description="The role assignment ID this item reviews (`target_id` when `target_type` is ROLE_ASSIGNMENT). ")
    status: CampaignItemStatusEnum
    created_at: datetime = Field(description="When the item was created (snapshotted into the campaign).")
    is_target_deleted: StrictBool = Field(description="True when the underlying role assignment is soft-deleted.")
    principal_id: Optional[UUID] = Field(default=None, description="Principal ID from the role assignment. Null if the RA is missing.")
    principal_type: Optional[EntityTypeEnum] = Field(default=None, description="Principal entity type. Null if the RA is missing.")
    entity_id: Optional[UUID] = Field(default=None, description="Entitlement entity ID. Null if the RA is missing.")
    entity_type: Optional[EntityTypeEnum] = Field(default=None, description="Entitlement entity type. Null if the RA is missing.")
    access_level: Optional[ResourceAccessLevel] = Field(default=None, description="Access level on the role assignment, if any.")
    access_level_name: Optional[StrictStr] = Field(default=None, description="Denormalized access level name stored on the campaign item.")
    reviews: List[CampaignItemReview] = Field(description="Reviewer assignments and decisions for this item.")
    admin_override: Optional[CampaignItemAdminOverride] = Field(default=None, description="Admin override, if any.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["campaign_item_id", "campaign_id", "target_type", "role_assignment_id", "status", "created_at", "is_target_deleted", "principal_id", "principal_type", "entity_id", "entity_type", "access_level", "access_level_name", "reviews", "admin_override"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CampaignItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_level
        if self.access_level:
            _dict['access_level'] = self.access_level.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reviews (list)
        _items = []
        if self.reviews:
            for _item_reviews in self.reviews:
                if _item_reviews:
                    _items.append(_item_reviews.to_dict())
            _dict['reviews'] = _items
        # override the default output from pydantic by calling `to_dict()` of admin_override
        if self.admin_override:
            _dict['admin_override'] = self.admin_override.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CampaignItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign_item_id": obj.get("campaign_item_id"),
            "campaign_id": obj.get("campaign_id"),
            "target_type": obj.get("target_type"),
            "role_assignment_id": obj.get("role_assignment_id"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "is_target_deleted": obj.get("is_target_deleted"),
            "principal_id": obj.get("principal_id"),
            "principal_type": obj.get("principal_type"),
            "entity_id": obj.get("entity_id"),
            "entity_type": obj.get("entity_type"),
            "access_level": ResourceAccessLevel.from_dict(obj["access_level"]) if obj.get("access_level") is not None else None,
            "access_level_name": obj.get("access_level_name"),
            "reviews": [CampaignItemReview.from_dict(_item) for _item in obj["reviews"]] if obj.get("reviews") is not None else None,
            "admin_override": CampaignItemAdminOverride.from_dict(obj["admin_override"]) if obj.get("admin_override") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


