# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from opal_security.models.paladin_context_source_kind import PaladinContextSourceKind
from opal_security.models.paladin_context_source_provider import PaladinContextSourceProvider
from typing import Optional, Set
from typing_extensions import Self

class CreatePaladinContextSourceInfo(BaseModel):
    """
    Information for adding a context source to a Paladin.
    """ # noqa: E501
    source_kind: PaladinContextSourceKind
    third_party_provider: PaladinContextSourceProvider
    remote_id: StrictStr = Field(description="The provider's identifier for the source. The Slack channel ID for a channel, or the Notion/Confluence page ID for a document.")
    name: Optional[StrictStr] = Field(default=None, description="An optional human-readable name for the source.")
    url: Optional[StrictStr] = Field(default=None, description="An optional link to the source.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["source_kind", "third_party_provider", "remote_id", "name", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePaladinContextSourceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePaladinContextSourceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_kind": obj.get("source_kind"),
            "third_party_provider": obj.get("third_party_provider"),
            "remote_id": obj.get("remote_id"),
            "name": obj.get("name"),
            "url": obj.get("url")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


