# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RequestTemplateCustomFieldTypeEnum(str, Enum):
    """
    The type of the custom request field. `CALLOUT` fields are display-only -- they show a message to the requester and collect no answer, so they never appear in a request's `custom_fields`.
    """

    """
    allowed enum values
    """
    SHORT_TEXT = 'SHORT_TEXT'
    LONG_TEXT = 'LONG_TEXT'
    BOOLEAN = 'BOOLEAN'
    MULTI_CHOICE = 'MULTI_CHOICE'
    MULTI_SELECT = 'MULTI_SELECT'
    CALLOUT = 'CALLOUT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RequestTemplateCustomFieldTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


