# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from opal_security.models.campaign_item_review_decision_enum import CampaignItemReviewDecisionEnum
from opal_security.models.campaign_item_reviewer_assignment_source_enum import CampaignItemReviewerAssignmentSourceEnum
from typing import Optional, Set
from typing_extensions import Self

class ReviewCampaignItemDecisionInfo(BaseModel):
    """
    A single reviewer decision to submit for a campaign item review. Mirrors GraphQL `CampaignItemReviewDecisionInput`. 
    """ # noqa: E501
    campaign_item_review_id: UUID = Field(description="The ID of the campaign item review to update.")
    decision: CampaignItemReviewDecisionEnum
    note: Optional[StrictStr] = Field(default=None, description="Optional note from the reviewer for this decision.")
    access_level_remote_id: Optional[StrictStr] = Field(default=None, description="Required when `decision` is `CHANGE_ROLE`. The remote ID of the access level to change to. Ignored for other decisions. ")
    new_reviewer_user_ids: Optional[List[UUID]] = Field(default=None, description="When `decision` is `REASSIGNED` and `assignment_source` is `MANUAL` or omitted, the user IDs to reassign this review to. ")
    assignment_source: Optional[CampaignItemReviewerAssignmentSourceEnum] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["campaign_item_review_id", "decision", "note", "access_level_remote_id", "new_reviewer_user_ids", "assignment_source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewCampaignItemDecisionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewCampaignItemDecisionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign_item_review_id": obj.get("campaign_item_review_id"),
            "decision": obj.get("decision"),
            "note": obj.get("note"),
            "access_level_remote_id": obj.get("access_level_remote_id"),
            "new_reviewer_user_ids": obj.get("new_reviewer_user_ids"),
            "assignment_source": obj.get("assignment_source")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


