# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RolePermissionNameEnum(str, Enum):
    """
    The name of the role permission.
    """

    """
    allowed enum values
    """
    READ = 'READ'
    READ_ASSIGNMENTS = 'READ_ASSIGNMENTS'
    CREATE = 'CREATE'
    IMPORT = 'IMPORT'
    EXPORT = 'EXPORT'
    SYNC = 'SYNC'
    DELETE = 'DELETE'
    READ_SETTINGS = 'READ_SETTINGS'
    EDIT_TAGS = 'EDIT_TAGS'
    EDIT_SETTINGS = 'EDIT_SETTINGS'
    EDIT_SYNC_SETTINGS = 'EDIT_SYNC_SETTINGS'
    EDIT_ASSIGNMENTS = 'EDIT_ASSIGNMENTS'
    EDIT_REQUEST_CONFIGURATIONS = 'EDIT_REQUEST_CONFIGURATIONS'
    EDIT_EVENT_STREAM = 'EDIT_EVENT_STREAM'
    ASSIGN_UAR_REVIEWERS = 'ASSIGN_UAR_REVIEWERS'
    SEND_REMINDERS = 'SEND_REMINDERS'
    STOP = 'STOP'
    REQUEST_ON_BEHALF = 'REQUEST_ON_BEHALF'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RolePermissionNameEnum from a JSON string"""
        return cls(json.loads(json_str))


