# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from opal_security.models.api_access_level_enum import ApiAccessLevelEnum
from typing import Optional, Set
from typing_extensions import Self

class Token(BaseModel):
    """
    A first-party API token.
    """ # noqa: E501
    token_id: StrictStr = Field(description="The ID of the API token.")
    created_at: datetime = Field(description="The date and time the token was created.")
    token_label: StrictStr = Field(description="A human-readable label for the token.")
    creator_user_id: StrictStr = Field(description="The ID of the user who created the token.")
    user_id: StrictStr = Field(description="The ID of the user the token authenticates as.")
    last_used_at: Optional[datetime] = Field(default=None, description="The date and time the token was last used.")
    access_level: ApiAccessLevelEnum
    expires_at: Optional[datetime] = Field(default=None, description="The date and time the token expires.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["token_id", "created_at", "token_label", "creator_user_id", "user_id", "last_used_at", "access_level", "expires_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Token from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Token from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "token_id": obj.get("token_id"),
            "created_at": obj.get("created_at"),
            "token_label": obj.get("token_label"),
            "creator_user_id": obj.get("creator_user_id"),
            "user_id": obj.get("user_id"),
            "last_used_at": obj.get("last_used_at"),
            "access_level": obj.get("access_level"),
            "expires_at": obj.get("expires_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


