# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from opal_security.models.entity_type_enum import EntityTypeEnum
from opal_security.models.viewer_campaign_item_review_decision_enum import ViewerCampaignItemReviewDecisionEnum
from typing import Optional, Set
from typing_extensions import Self

class ViewerCampaignItem(BaseModel):
    """
    A campaign review item assigned to the current viewer, matching GraphQL `ViewerCampaignItem`. 
    """ # noqa: E501
    campaign_item_review_id: UUID = Field(description="The ID of the campaign item review.")
    decision: Optional[ViewerCampaignItemReviewDecisionEnum] = Field(default=None, description="The reviewer's decision. Null when undecided.")
    note: Optional[StrictStr] = Field(default=None, description="Optional note from the reviewer.")
    decided_at: Optional[datetime] = Field(default=None, description="When the decision was finalized.")
    pending_decision: Optional[ViewerCampaignItemReviewDecisionEnum] = Field(default=None, description="Pending decision staged by the viewer, if any.")
    pending_note: Optional[StrictStr] = Field(default=None, description="Pending note attached to the reviewer's pending decision.")
    updated_access_level_remote_id: Optional[StrictStr] = Field(default=None, description="Target access level remote ID when decision is CHANGE_ROLE.")
    pending_updated_access_level_remote_id: Optional[StrictStr] = Field(default=None, description="Pending target access level remote ID when decision is CHANGE_ROLE.")
    reassigned_to_reviewer_ids: Optional[List[UUID]] = Field(default=None, description="User IDs this review was reassigned to.")
    principal_id: UUID = Field(description="Principal ID from the role assignment.")
    principal_type: EntityTypeEnum
    entity_id: UUID = Field(description="Entity ID from the role assignment.")
    entity_type: EntityTypeEnum
    access_level_name: Optional[StrictStr] = Field(default=None, description="Denormalized access level name.")
    access_level_remote_id: Optional[StrictStr] = Field(default=None, description="Access level remote ID from the role assignment.")
    granted_at: datetime = Field(description="When the access was originally granted.")
    expires_at: Optional[datetime] = Field(default=None, description="When the access expires, if set.")
    role_assignment_id: UUID = Field(description="ID of the underlying role assignment.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["campaign_item_review_id", "decision", "note", "decided_at", "pending_decision", "pending_note", "updated_access_level_remote_id", "pending_updated_access_level_remote_id", "reassigned_to_reviewer_ids", "principal_id", "principal_type", "entity_id", "entity_type", "access_level_name", "access_level_remote_id", "granted_at", "expires_at", "role_assignment_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ViewerCampaignItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ViewerCampaignItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign_item_review_id": obj.get("campaign_item_review_id"),
            "decision": obj.get("decision"),
            "note": obj.get("note"),
            "decided_at": obj.get("decided_at"),
            "pending_decision": obj.get("pending_decision"),
            "pending_note": obj.get("pending_note"),
            "updated_access_level_remote_id": obj.get("updated_access_level_remote_id"),
            "pending_updated_access_level_remote_id": obj.get("pending_updated_access_level_remote_id"),
            "reassigned_to_reviewer_ids": obj.get("reassigned_to_reviewer_ids"),
            "principal_id": obj.get("principal_id"),
            "principal_type": obj.get("principal_type"),
            "entity_id": obj.get("entity_id"),
            "entity_type": obj.get("entity_type"),
            "access_level_name": obj.get("access_level_name"),
            "access_level_remote_id": obj.get("access_level_remote_id"),
            "granted_at": obj.get("granted_at"),
            "expires_at": obj.get("expires_at"),
            "role_assignment_id": obj.get("role_assignment_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


