# coding: utf-8

"""
    Opal API

    The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

    The version of the OpenAPI document: 1.0
    Contact: hello@opal.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from opal_security.models.webhook_api_key_credential import WebhookApiKeyCredential
from opal_security.models.webhook_auth_type_enum import WebhookAuthTypeEnum
from opal_security.models.webhook_hmac_credential import WebhookHmacCredential
from typing import Optional, Set
from typing_extensions import Self

class WebhookCredentials(BaseModel):
    """
    Authentication credentials for a webhook connection.
    """ # noqa: E501
    auth_type: WebhookAuthTypeEnum
    api_key_credentials: Optional[List[WebhookApiKeyCredential]] = Field(default=None, description="API key credentials, present when auth_type is API_KEY.")
    hmac_credential_1: Optional[WebhookHmacCredential] = Field(default=None, description="Primary HMAC credential, present when auth_type is HMAC.")
    hmac_credential_2: Optional[WebhookHmacCredential] = Field(default=None, description="Secondary HMAC credential for rotation, present when auth_type is HMAC.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auth_type", "api_key_credentials", "hmac_credential_1", "hmac_credential_2"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api_key_credentials (list)
        _items = []
        if self.api_key_credentials:
            for _item_api_key_credentials in self.api_key_credentials:
                if _item_api_key_credentials:
                    _items.append(_item_api_key_credentials.to_dict())
            _dict['api_key_credentials'] = _items
        # override the default output from pydantic by calling `to_dict()` of hmac_credential_1
        if self.hmac_credential_1:
            _dict['hmac_credential_1'] = self.hmac_credential_1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hmac_credential_2
        if self.hmac_credential_2:
            _dict['hmac_credential_2'] = self.hmac_credential_2.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth_type": obj.get("auth_type"),
            "api_key_credentials": [WebhookApiKeyCredential.from_dict(_item) for _item in obj["api_key_credentials"]] if obj.get("api_key_credentials") is not None else None,
            "hmac_credential_1": WebhookHmacCredential.from_dict(obj["hmac_credential_1"]) if obj.get("hmac_credential_1") is not None else None,
            "hmac_credential_2": WebhookHmacCredential.from_dict(obj["hmac_credential_2"]) if obj.get("hmac_credential_2") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


